#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : source-code-pro
Version  : 1.050r.it
Release  : 5
URL      : https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
Source0  : https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : OFL-1.1
Requires: source-code-pro-data = %{version}-%{release}
Requires: source-code-pro-license = %{version}-%{release}
Patch1: 0001-makefile.patch

%description
# Source Code Pro
Source Code Pro is a set of OpenType fonts that have been designed to work well
in user interface (UI) environments. In addition to a functional OpenType font, this open
source project provides all of the source files that were used to build this OpenType font
by using the AFDKO makeotf tool.

%package data
Summary: data components for the source-code-pro package.
Group: Data

%description data
data components for the source-code-pro package.


%package license
Summary: license components for the source-code-pro package.
Group: Default

%description license
license components for the source-code-pro package.


%prep
%setup -q -n source-code-pro-2.030R-ro-1.050R-it
cd %{_builddir}/source-code-pro-2.030R-ro-1.050R-it
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604355639
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604355639
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/source-code-pro
cp %{_builddir}/source-code-pro-2.030R-ro-1.050R-it/LICENSE.txt %{buildroot}/usr/share/package-licenses/source-code-pro/689c1517e0db480765a3c35f13a7d942779d7e5e
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Black.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-BlackIt.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Bold.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-BoldIt.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-ExtraLight.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-ExtraLightIt.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-It.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Light.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-LightIt.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Medium.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-MediumIt.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Regular.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Semibold.otf
/usr/share/fonts/adobe-source-code-pro/SourceCodePro-SemiboldIt.otf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/source-code-pro/689c1517e0db480765a3c35f13a7d942779d7e5e
